### ISSUE TITLE
pulls steam username instead of player name for the first few seconds

### ISSUE THREAD

**Issue by cutemaxxing** [steezeburger/palguybuddydude#2] opened 2024-02-07 16:37 UTC
when someone logs in and their steam username is different than their ingame name, the bot double posts by posting the steam username as the first player joining, then it gets their actual ingame name and then posts their ingame name as another player joining, then it posts the steam username as a player that left.

it gets a bit confusing as it makes it look like there are multiple people joining the server 

image attached for clarity, blue is the steam username, pink is the ingame name.

![image](https://github.com/steezeburger/palguybuddydude/assets/101653707/57f4955f-5094-4d97-8e3d-142f89902c78)

**Comment by steezeburger** [comment] 2024-02-08 22:51
I have noticed this too, but did not have time to track down the cause.
Thank you for this. I will try to patch this up after work today!

**Comment by steezeburger** [comment] 2024-02-09 02:14
@majokko The issue should be fixed now!

To upgrade, you can pull latest changes then
```bash
docker compose stop
docker compose build
docker compose up -d
```

**Comment by steezeburger** [comment] 2024-02-09 19:59
Reopening as my fix didn't work for every case it seems. Kind of a tricky one. Will debug again this weekend.

**Comment by steezeburger** [comment] 2024-02-11 06:32
Fixed in https://github.com/steezeburger/palguybuddydude/commit/e66f3b0916c696da61e0f9ede61b17cc659befec

```
palguybuddydude      | 2024/02/11 06:29:08 Current players: [{Name:BartSimpson PlayerUID:00000000 SteamID:<REDACTED>}]
palguybuddydude      | 2024/02/11 06:29:08 Skipping fake duplicate player: {Name:BartSimpson PlayerUID:00000000 SteamID:<REDACTED>}
```

**Closed as completed by steezeburger** 2024-02-11 06:32 UTC
Labels: bug
